name: intl_flavors
description: Intl utility to manage multi ARB files to manage flavors in your app
version: 0.0.2
homepage: https://github.com/jaumard/intl_flavors

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:

dev_dependencies:
  test:
