name: jimtl_codegen_example
description: Intl utility to manage multi ARB files to manage flavors in your app
version: 0.0.1
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  intl:
  jimtl:

dev_dependencies:
  build_runner: ^2.0.3
  jimtl_codegen:
    path: ../

dependency_overrides:
  jimtl:
    path: ../../jimtl