targets:
  intl_flavor_codegen:intl_flavor_codegen:
    builders:
      intl_flavor_codegen|intlBuilder:
        enabled: true
        generate_for:
          - lib/*

builders:
  intlBuilder:
    import: 'package:intl_flavor_codegen/intl_flavor_codegen.dart'
    builder_factories: ['intlBuilder']
    build_extensions: { '.arb': ['messages.en.dart'], '.dart': [ '.arb' ] }
    build_to: source
    auto_apply: root_package
