name: intl_flavor_codegen
description: Intl utility to manage multi ARB files to manage flavors in your app
version: 0.0.1
homepage: https://github.com/jaumard/intl_flavors

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  analyzer:
  build:
  build_resolvers:
  meta:
  path:
  source_gen:
  intl_generator: ^0.1.0
    #path: ../../../../StudioProjects/intl_translation
  intl_flavor:
    path: ../intl_flavor

dev_dependencies:
  build_runner: ^2.0.3
  build_config: ^1.0.0
  build_test: ^2.1.0
  coverage: ^1.0.2
  logging: ^1.0.1
  mocktail: ^0.1.2
  test: ^1.16.8