builders:
  intlBuilder:
    import: 'package:intl_flavors_codegen/intl_flavors_codegen.dart'
    builder_factories: ['intlBuilder']
    build_extensions: { '.dart': [ '.arb' ] }
    build_to: source
    auto_apply: dependents
    applies_builders: [ "source_gen|combining_builder" ]
