name: intl_flavors_codegen
description: Intl utility to manage multi ARB files to manage flavors in your app
version: 0.0.1
homepage: https://github.com/jaumard/intl_flavors

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  analyzer: ">=1.5.0 <2.0.0"
  build: ">=2.0.1 <3.0.0"
  path: ">=1.8.0 <2.0.0"
  source_gen: ">=1.0.0 <2.0.0"
  intl: ">=0.17.0 <1.0.0"
  intl_generator: ">=0.1.0 <1.0.0"
    #path: ../../../../StudioProjects/intl_translation
  intl_flavors: #">=0.0.1 <1.0.0"
    path: ../intl_flavors

dev_dependencies:
  build_runner: ^2.0.3
  test: ^1.16.8